replicaCount: 1

image:
  repository: ghcr.io/dinosath/oasgen-k8s
  tag: main
  pullPolicy: IfNotPresent

imagePullSecrets: []

podAnnotations: {}


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 5m
    memory: 10Mi